@startuml c2
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

Container(browser, "Browser", "Chrome, Firefox, IE, etc", "Internet browser, used to access CharlesCD interface.")
Container(moove, "CharlesCD-Moove", "Kotlin, SpringBoot", "API Application: Process and stores information in the database about users, applications and configurations in general in the database. It orchestrates the requests for other applications.")
Container(compass, "CharlesCD-Compass", "Golang", "Process metrics from the provider registered by the user and provide them via JSON/HTTPS API.")

Container_Boundary(charlescd_ui, "CharlesCD UI"){
   
    Component(routes, "Router", "React-Router-Dom, Typescript", "Through the routes system, it knows which module needs to render.")
    Component(module, "Module", "ReactJS, typeScript", "The module uses a CharlesCD fetch implementation to make HTTP requests. Based on the response it populates the screen.")
    Component(component, "Component", "ReactJS, TypeScript, react-hook-form", "Check out more about components in the Storybook page.")
    Component(provider, "Provider", "URL Request, Typescript", "Receives information about the current deployment state and then sends the state you want to the operator synchronize and make the reconcile.")
   
    
    Rel(routes, module, "It uses")
    Rel(module, component, "It uses")
    Rel(module, provider, "Fetch")
    Rel(provider, moove, "Makes the request via HTTPS/JSON")
    Rel(provider, compass, "Makes the request via HTTPS/JSON")
    
}

Rel(browser, routes, "Makes the request", "JSON/HTTPS")
@enduml
