@startuml c2
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

Container(browser, "Browser", "Chrome, Firefox, IE, etc", "Navegador de Internet usado para acessar a interface do CharlesCD.")
Container(moove, "CharlesCD-Moove", "Kotlin, SpringBoot", "API Application: Processa e armazena no banco de dados as informações dos usuários, aplicações e configurações em geral. Orquestra as requisições para as outras aplicações.")
Container(compass, "CharlesCD-Compass", "Golang", "Processa as métricas consumidas do provedor cadastrado pelo usuário e as fornece via JSON/HTTPS API.")

Container_Boundary(charlescd_ui, "CharlesCD UI"){
   
    Component(routes, "Router", "React-Router-Dom, Typescript", "Por meio do sistema de rotas, saber qual módulo deve ser renderizado.")
    Component(module, "Module", "ReactJS, typeScript", "O módulo usa uma implementação do CharlesCD do fetch para fazer requisições HTTP e, a partir da resposta, ele popula a tela.")
    Component(component, "Component", "ReactJS, TypeScript, react-hook-form", "Para visualizar melhor os compontents, acesse a página do Storybook.")
    Component(provider, "Provider", "URL Request, Typescript", "Recebe as informações do estado atual de um deploy e envia o estado desejado para que operator sincronize e faça o reconcile.")
   
    
    Rel(routes, module, "Usa")
    Rel(module, component, "Usa")
    Rel(module, provider, "Fetch") 
    Rel(provider, moove, "Faz a requisição via HTTPS/JSON")
    Rel(provider, compass, "Faz a requisição via HTTPS/JSON")
   
}

Rel(browser, routes, "Faz a requisição", "JSON/HTTPS")
@enduml
