@startuml c1
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

Person(user, "Desenvolvedor/QA/PM/Gestor/Supervisor/Etc", "Qualquer pessoa que possui alguma aplicação com os deploys gerenciados pelo CharlesCD.")

System(charlescd_system, "Sistema CharlesCD", "Ferramenta de deploy contínuo orientada a hipóteses.")
System_Ext(kubernetes, "Kubernetes")

Rel(user, charlescd_system, "Gerencia os seus deploys")
Rel(charlescd_system, kubernetes, "Implanta atualizações no cluster Kubernetes")
Rel(charlescd_system, user, "Envia o retorno dos eventos")


@enduml
