@startuml c1
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

Person(user, "Developer/QA/PM/Manager/Supervisor/Etc", "Anyone who has an application with deployments managed by CharlesCD.")

System(charlescd_system, "CharlesCD System", "Hypothesis-oriented continuous deployment tool.")
System_Ext(kubernetes, "Kubernetes")

Rel(user, charlescd_system, "Manages your deployments")
Rel(charlescd_system, kubernetes, "Deploys updates to your Kubernetes cluster")
Rel(charlescd_system, user, "Sends the events returns")


@enduml
