#
  # Copyright 2020, 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #  http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.

name: OfficialDoc

on:
  push:
    branches: [ main ]

env:
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ AWS_REGION }}

jobs:
  predoc_deploy_c4model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: $AWS_REGION
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: OfficialDocS3Session
          role-skip-session-tagging: true

      - name: Remove Custom C4Builder Theme from S3
        uses: vitorsgomes/s3-rm-action@master
        with:
          args: --recursive
        env:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_REGION: $AWS_REGION
          PATH_TO_DELETE: /c4model/theme/
    

      - name: Upload Custom C4Builder Theme CSS on S3
        run: aws s3 sync --follow-symlinks assets/css s3://$AWS_S3_BUCKET/c4model/theme/       

      - name: Upload Custom C4Builder Theme JS on S3
        run: aws s3 sync --follow-symlinks assets/js s3://$AWS_S3_BUCKET/c4model/theme/ 

      - name: C4Builder PT-BR
        uses: ZupIT/c4builder-action@v1.0.3
        with:
          path: 'pt-br'

      - name: Upload PT-BR on S3
        run: aws s3 sync --follow-symlinks pt-br/docs s3://$AWS_S3_BUCKET/c4model/pt-br/ --delete

      - name: C4Builder EN
        uses: ZupIT/c4builder-action@v1.0.3
        with:
          path: 'pt-br'  

      - name: Upload EN on S3
        run: aws s3 sync --follow-symlinks en/docs s3://$AWS_S3_BUCKET/c4model/en/ --delete

 